### ISSUE TITLE
Handle CaptchaValidator exception thrown on wrong configuration.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/securify#100]
Exception thrown in [CaptchaValidator](https://github.com/magento/security-package/blob/d11e86b0e3ec0c570b4d55a3725e7e1278dfdb1f/ReCaptcha/Model/CaptchaValidator.php#L42 ) is now never caught and processed.

**Comment by naydav** [comment]
Closed in favor of https://github.com/magento/security-package/pull/125
