### ISSUE TITLE
Add reCAPTCHA to authentication form on Checkout page.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/securify#118]
### Preconditions (*)

1. Customer created.
2. Virtual product created.
3. reCAPTCHA enabled.

### Steps to reproduce (*)

1. As a Guest, add Virtual Product to Cart.
2. Proceed to Checkout.
3. On the Checkout page, try to login as Customer.

### Expected result (*)

1. reCAPTCHA should be present in login form.
2. Login is successful.

### Actual result (*)

1. reCAPTCHA absent in login form.
2. Login is unsuccessful.

**Comment by sdzhepa** [comment]
Hello @engcom-Delta 

Could you please check and confirm that the issue has been fixed?

**Need to test**
- checkout with the virtual type products
- login during checkout with virtual type products
- all reCAPCTHA types

**Comment by engcom-Delta** [comment]
@sdzhepa I rechecked and this issue is fixed.

**Comment by naydav** [comment]
Closed due to the comment from @engcom-Delta.
