### ISSUE TITLE
[QA] Define and analyze required test-case coverage for functionality "security.txt"

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#126]
**TODO:**
1. Install Magento instance based on `2.4-develop` branch with security-package on `develop` branch
2. Review and analyze current MFTF coverage for security.txt module

- https://github.com/magento/security-package/tree/develop/Securitytxt/Test/Mftf

3. Create manual test-cases coverage in HiptTest as a part of security-package/security.txt.

- Link to HipTest project: https://studio.cucumber.io/projects/169934/test-plan/folders/1253526
- Example/Template of test-case: https://studio.cucumber.io/projects/169934/test-plan/folders/1245963/scenarios/4327163

4. Define do we need to add additional test-cases to HipTest that were missed in MFTF coverage, if any

 **Additional:**
- documentation related to this module: https://github.com/magento/security-package/tree/1.0-develop/Securitytxt

**Comment by engcom-Delta** [comment]
For now configuration scope for Security.txt is defined as by `store view`
![image](https://user-images.githubusercontent.com/51681379/76086182-45eef500-5fbc-11ea-83de-697ef57d6422.png)
That leads to following issue: configuration cannot be saved in scope that is different from `Default Config`

**Steps to reproduce:**
1. Create Website:
a. Name = United Kingdom 
b. Code = uk_website 
c. Sort Order = 1

2. Create Store :
a.	Web Site = United Kingdom
b.	Name = UK
c.	Code = uk_store
d.	Root Category = Default Category

3. Create Store View:
a.	Store = UK
b.	Name =  UNITED KINGDOM - ENGLISH
c.	Code = uk_en
d.	Status = Enabled
e.	Sort Order = 1

4. Enable Security.txt and fill all fileds
5. Go to Stores->Configuration
6. Change `Scope:` to `United Kingdom`
7. Edit some fields and click `Save Config`
**Result:**
:x: Configuration is not saved for current website scope
![image](https://user-images.githubusercontent.com/51681379/76087015-fb6e7800-5fbd-11ea-81ae-1c0ccade5f8c.png)

8. Change `Scope:` to `UNITED KINGDOM - ENGLISH`
9. Edit some fields and click `Save Config`
**Result:**
:x: Configuration is not saved for current store view scope
![image](https://user-images.githubusercontent.com/51681379/76087141-396b9c00-5fbe-11ea-87cd-78df1c888043.png)

**Comment by sdzhepa** [comment]
Thank you @engcom-Delta 
I have cerated https://github.com/magento/security-package/issues/127

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Story
