### ISSUE TITLE
ForgotPasswordFormTest and LoginFormTest are failing.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/securify#135]
Magento\ReCaptchaUser\Test\Integration\ForgotPasswordFormTest and Magento\ReCaptchaUser\Test\Integration\LoginFormTest are failing with message
`Return value of Mock_Validator_eb342960::isValid() must be an instance of Magento\Framework\Validation\ValidationResult, bool returned`

**Comment by naydav** [comment]
Was fixed in scope of https://github.com/magento/security-package/pull/119
