### ISSUE TITLE
[QA] Cycle1: Feature testing for reCAPCTHA

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#137]
**Goal**
- Need to confirm that after all development feature has expected quality status
- Need to confirm that created test coverage is enough 

**Entry Criteria**
- [x] https://github.com/magento/security-package/issues/130 is completed 
- [x] All development work related to changes/refactoring functionality should be completed and merged.

**Requirements** 
- [x] Test Cycles 1 based on CucumberStution test-cases are created 
- [x] All test cases are executed on all planed editions
- [x] All found bugs are created as separate Issue in this repo
- [x] Based on the result of Cycle 1 should be decided do we need additional Cycle 2 or can verify all found bugs during PR delivery

**Exit Criteria**
- [x] All found bugs are triaged( Must have to fix/can be postponed)
- [x] All Critical and must have bugs are fixed and verified - qa passed
- [ ]  All found gaps in test coverage should be resolved(if any)

**Comment by sdzhepa** [comment]
To: @naydav 
cc: @engcom-Delta @engcom-Foxtrot 

Based on QA report:

It seems we do not ready to start Final testing after development complete because right now we have a couple of PRs related to reCAPCHA that still not merged.
So, in general, we can start our "final" testing right now based on [Cycle 1: Final feature testing for reCAPCTHA](https://studio.cucumber.io/projects/169934/test-runs/378772/overview) and execute **52** planned test cases it will take 1-2 days but after merging all PRs we need to perform the additional test-cycle with the same amount of test-cases.

List of Prs that affect final testing
1. https://github.com/magento/security-package/pull/147
- Affects a couple of test cases related to disabling reCapcha from CLI. 

2.  https://github.com/magento/security-package/pull/146
- not clear from the description of what functionality will be affected

3.  https://github.com/magento/security-package/pull/142
-  not big impact but still some test cases could be Fai;ed

4.  https://github.com/magento/security-package/pull/133
- not clear what functionality potentially could be affected after these changes 

5.  https://github.com/magento/security-package/pull/132
- not clear what functionality potentially could be affected after these changes 

6.  https://github.com/magento/security-package/pull/61
- IMO: theoretically this part could be tested later in additional small test-cycle but would be grate to have it meged

**Comment by sdzhepa** [comment]
Due to no answer, we decided to start the first Cycle on the not final Code-Base
It seems we sill need to run additional Cycle 2 after all code will be merged

Update:
FYI:  @naydav @engcom-Foxtrot

One critical bug is found https://github.com/magento/security-package/issues/148

**Comment by naydav** [comment]
@sdzhepa 
All PR's except https://github.com/magento/security-package/pull/61 were merged.
Thanks for notification

**Comment by sdzhepa** [comment]
The first cycle for reCAPTCHA has been completed.
The additional scope was tested in the scope of each PRs.

Due to additional changes and fixes related to reCAPCTHA we need to run the next cycle 2.

I am closing this task and create new for Cycle 2 https://github.com/magento/security-package/issues/201
