### ISSUE TITLE
reCAPTCHA v2 ("I am not a robot") can be applied for Newsletter Subscription

### ISSUE THREAD

**Issue by VasylShvorak** [magento/securify#144]
### Preconditions (*)

1. Magento 2.4-develop with security-package

### Steps to reproduce (*)

1. Go to Stores->Configuration->Security->Google reCAPTCHA Storefront
2. Click on **Storefront** tab

### Expected result (*)

1. Only Invisible reCAPTCHA can be applied for "Enable Invisible reCAPTCHA in Newsletter Subscription"

### Actual result (*)

1. reCAPTCHA v2 ("I am not a robot") is available as option for "Enable Invisible reCAPTCHA in Newsletter Subscription"
![image](https://user-images.githubusercontent.com/26908019/76517477-0a45a680-6466-11ea-84a6-069fe7f98324.png)

**Comment by naydav** [comment]
Duplicate of https://github.com/magento/security-package/issues/104
After a restructuring of configuration, we can apply all types of reCAPTCHA to Newsletter
