### ISSUE TITLE
Investigate possibility to use recaptcha with paypal payments

### ISSUE THREAD

**Issue by engcom-Delta** [magento/securify#153]
### Summary (*)

Use Google’s reCAPTCHA  to prevent bots from aggressively scripting and pushing through transactions in an automated way.

### Examples (*)

Recapthca badge will be conditionally (or always) shown on checkout page:
![image](https://user-images.githubusercontent.com/51681379/77148031-637d8d80-6a97-11ea-8789-f773d91dd26d.png)

### Proposed solution

Add possibility to enable recaptcha for paypal payments

**Comment by engcom-Foxtrot** [comment]
Issues for missing reCAPTCHA created:
https://github.com/magento/security-package/issues/154
https://github.com/magento/security-package/issues/156
https://github.com/magento/security-package/issues/157
PR for Paypal already exists:
https://github.com/magento/security-package/pull/61
