### ISSUE TITLE
[DOC] Create-update documentation related to reCAPTCHA chanages

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#159]
**Required types of documentation:**
- README.md
- [Magento DevDoc](https://devdocs.magento.com/#/individual-contributors)
- [Magento User Docs](https://docs.magento.com/m2/ce/user_guide/getting-started.html) (if applicable)

**Note:**
- an approach, where should be placed documentation, will be defined later(as a part of the module or as a page on Dev/Merch docs)

**Links and materials** 
- Official Google Documentation: https://developers.google.com/recaptcha/docs/versions

Old and outdated documentation. Must be updated according to the newest changes
- Magento DevDocs: https://devdocs.magento.com/guides/v2.3/security/google-recaptcha.html 
- Magento User Docs: https://docs.magento.com/m2/ce/user_guide/stores/security-google-recaptcha.html

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by dineshvb** [comment]
https://github.com/magento/devdocs/pull/8437 - Related DEVDOCS PR

**Comment by keharper** [comment]
@sdzhepa Would you review the devdocs PR (or assign someone)?

**Comment by sdzhepa** [comment]
Hello @keharper 

Sorry for the very late response
Unfortunately, I and my team are not working on this  project (security-package) anymore
