### ISSUE TITLE
Storefront is not available if install security-package from meta-package and execute "bin/magento setup:di:compile"

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#168]
### Preconditions (*) install security-package in the next way; 
NOTE: [flow the similar as described for MSI](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide)
1. Create `magento2` as a root folder for installation
2. clone magento2 ce `2.4-develop` branch into `magento2`
`git clone -b 2.4-develop --single-branch https://github.com/magento/magento2.git magento2`
3. clone security-package `1.0-develop` into `magento2/ext/magento/security-package`
`git clone -b 1.0-develop --single-branch https://github.com/magento/security-package.git magento2/ext/magento/security-package`
4. Run next common from the root folder to configure composer
```
composer config minimum-stability dev
composer config repositories.ext path ./ext/*/*/*
composer require magento/security-package
```
5. Install magento
6. Run compilation from root folder
`
bin/magento setup:di:compile
`

### Steps to reproduce (*)

1. Go to Magneto Admin Panel
2. Configure and enable reCaptcha on the storefront. Example of my setting 
![213](https://user-images.githubusercontent.com/3409584/77802546-16765a00-7049-11ea-9f56-ac365d76d28d.png)

3. Go to Storefront

### Expected result (*)
1. Storefront is available
2. No erros
3. reCAPCTHA is working

### Actual result (*)
1. blank page
2. Error in system.log
```
[2020-03-27 20:55:11] main.CRITICAL: Error: Cannot instantiate interface Magento\ReCaptchaValidationApi\Api\Data\ValidationConfigExtensionInterface in /var/www/magento/instance_1/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121

[2020-03-27 20:55:13] main.CRITICAL: Error: Cannot instantiate interface Magento\ReCaptchaValidationApi\Api\Data\ValidationConfigExtensionInterface in /var/www/magento/instance_1/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121
```

**Comment by naydav** [comment]
https://github.com/magento/security-package/pull/169
