### ISSUE TITLE
Update README.md for Security.txt module

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#177]
File: https://github.com/magento/security-package/blob/1.0-develop/Securitytxt/README.md

TODO:
1. Update link to the latest version of the convention: https://tools.ietf.org/html/draft-foudil-securitytxt-09
2.  Update summary quote from the latest convention (Abstract section)
3. review update section `A valid security.txt file could look like the following example:`
- the example should reflect requirements from the convention. e.g. all contact emails should start from "mailto:" 
 

> "mailto" and "tel" URI schemes must be used when
>    specifying email addresses and telephone numbers, as defined in
>    [RFC6068] and [RFC3966]

**Comment by naydav** [comment]
https://github.com/magento/security-package/pull/178
