### ISSUE TITLE
Not possible to use the most part of predefined templates 

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#180]
### Preconditions (*)
1. Install Magento using security-package
```
mkdir magento2
git clone -b 2.4-develop --single-branch https://github.com/magento/magento2.git magento2
git clone -b 1.0-develop --single-branch https://github.com/magento/security-package.git magento2/ext/magento/security-package
cd magento2
composer config minimum-stability dev
composer config repositories.ext path ./ext/*/*/*
composer require magento/security-package
```

### Steps to reproduce (*)
1. Go to _SYSTEM > Notifier > Manage Templates_
2. Click "New Templates"
3.  Scroll down to the "Copy from system template:" drop-down
4. Select any template from group 
- **Email specific templates**
- **Slack Messenger specific templates**
- **Telegram Messenger specific templates**
5. Click "Copy" button

### Expected result (*)

1. Selected template is loaded and inserted into "Template" text-box
2. Should be the possibility to load all templates from all groups
3. Only one "*" should be for "Template" box - to mark it as required

### Actual result (*)

1. Only templates from group **Generic Templates** can be loaded
3. All other leads to JS error and do not load
![templates](https://user-images.githubusercontent.com/3409584/78189530-ced04380-7437-11ea-8aa8-fbff30ce3619.png)

**Comment by engcom-Kilo** [comment]
Some confusion with templates in select.

Templates that called - **Default Event Template** & **Default Event Template**
Should to include in all Options group (_Email specific templates, Slack Messenger specific templates, Telegram Messenger specific templates_)?

Or only to **_Generic Templates_** ?

![New_Template___Notifier___System___Magento_Admin](https://user-images.githubusercontent.com/60192090/78275708-a1a89180-751a-11ea-9134-de14f7cf2654.jpg)
