### ISSUE TITLE
Recaptcha is not required for PayPal PayflowPro payment form 

### ISSUE THREAD

**Issue by engcom-Delta** [magento/securify#197]
### Preconditions (*)

1. Configure PayPal PayflowPro
2. Configure reCAPTCHA v2 ("I am not a robot")
3. Simple product is created

### Steps to reproduce (*)

1. Set Enable for PayPal PayflowPro payment form=reCAPTCHA v2 ("I am not a robot")
2. Add product to cart
3. Click Proceed to Checkout
4. Fill Shipping Address fields and click Next
5. Choose Credit Card (Payflow Pro)
6. Fill all required fields
7. Don't check recaptcha checkbox
8. Click Place Order

### Expected result (*)

1. Order cannot be placed if recaptcha is unchecked

### Actual result (*)

1. Order is placed successfully
2. Payment form is submitted without recapthca verification

**Comment by naydav** [comment]
https://github.com/magento/security-package/pull/175
