### ISSUE TITLE
[INVESTIGATE] Support Google Recaptcha on guest checkout flow

### ISSUE THREAD

**Issue by sdzhepa** [magento/securify#202]
### Description

Based on request from Product Manager "Support Google Recaptcha on guest checkout flow" need to do investigate how it can be done from the tech/dev perspectiv.

TODO:
- Investigate posibility(best approach) to add reCAPCTHA on the Payment Step of Checekout only for Guest Checkout(not registered customer)
- what is the proposed solution to avoid 2 reCAPCTHA in case with PayPal
- how to avoid performance degradation(if any) for Checkout flow
- what additional(hiden) dificulties could be during and after this implementation

### Initial description of request from Product Manager 

As Magento Merchant, I want reCAPTCHA to be added on guest checkout page of storefront so that a malicious user cannot perform spam ordering (A bot testing huge volumes of cards on the store) on my web-store

AC:

- On the admin panel, Under Google reCAPTCHA storefront add a field "Enable for guest checkout" with a drop-down with option to enable the supported reCAPTCHA /disable
- On choosing a reCAPTCHA type, the guest checkout should show & support the reCAPTCHA in the guest checkout flow
- If reCAPTCHA is not enabled on admin panel, the guest checkout flow should not show reCAPTCHA on guest checkout page
The default option for the "Enable for guest checkout" would be No/disabled

### Some comments/disussion
```
1. In current Checkout implementation on the "Payment step" Magento has a separate section per each Payment Method with its own "Place Order" button.

- if we add reCAPCTHA near the "Place Order" button, it seems we will have several reCAPCTHA blocks per each Payment Solution. Possible performance degradation on this flow
- What is expected behavior if a user opens one payment method, complete reCAPCTHA challenge but then use another payment
See example example_checkout1.mp4

2. User flows if reCAPCTHA for PayPal is enabled

- Guest Customer checkout
- Registered Customer checkout
- Customer Login during checkout
- how to avoid case with 2 reCAPCTHA

3. What expected result if no "No Payment Information Required"
100% discount and Free Shipping
GiftCard covered 100% price
See example example_checkout1.mp4
```

![2020-04-09_14-39-55](https://user-images.githubusercontent.com/3409584/78934250-36a61000-7a70-11ea-927a-ab38b2a78178.gif)

**Comment by engcom-Kilo** [comment]
Can add reCaptcha to Submit order button section, before-place-order block.
Can add like Agreement checkbox.
Validation for reCaptcha use Plugin also like Agreement functional, use plugin for beforeSavePaymentInformationAndPlaceOrder.

Can not add validation reCaptcha use Observers, because need check before Place order.

"how to avoid performance degradation(if any) for Checkout flow"
- in some cases, Google servers for validation reCaptcha can be unavailable,
for these cases I think better skip validation reCaptcha. Because if servers of Google unavailable - this can be block order creation process.

"what additional(hiden) dificulties could be during and after this implementation"
- I think big problem for reCaptcha on checkout page, this is not loaded JS script from Google,
if JS script not loaded (for example low internet connection), reCaptcha will not rendered.
And when client try to create order, will returned error message.

- Also if API keys changed, will returned broken reCaptcha, and can not create order.

**Comment by engcom-Kilo** [comment]
created locale example for reCaptcha on Checkout page

![Checkout-captcha](https://user-images.githubusercontent.com/60192090/78995477-17c87c00-7b4b-11ea-934a-e2ac4269ab5c.jpg)

**Comment by engcom-Kilo** [comment]
If checkout page with few different payment methods - reCaptcha will present for each method, near button (section) Place Order.

For example on checkout page present 2 payment methods Money Order, Bank Transfer.
**For each payment method tab - will render reCaptcha block.**

- If user select Money Order Payment and checked reCaptcha near Place Order button,
and Switched to Bank Transfer Payment - reCaptcha will unchecked in this tab.

- If user switched back to Money Order Payment  - reCaptcha will checked.

- State of reCaptcha not reloaded, only can reloaded - if timeout (seems 1 min).

- If custom payment method  and not present Place Order section, reCaptcha not will be rendering.

**Comment by engcom-Kilo** [comment]
In case with PayPal Payflow method - right now implemented reCaptcha, 
if add reCaptcha to each Payment methods - can be present 2 reCaptcha block, 
can add some logic for skip this case.

![Checkoutpp](https://user-images.githubusercontent.com/60192090/79006115-199d3a00-7b61-11ea-9520-feef709e98aa.jpg)




Seems better, when can exist setting for each Payment method where need to add  reCaptcha block.

**Comment by sdzhepa** [comment]
Thank you @engcom-Kilo 

@naydav could you please have a look when you will have time?

**Comment by sdzhepa** [comment]
Due to no additional request and feedback here,
I think we can close this issue.

Thank you @engcom-Kilo for investigating and detailed comments
