### ISSUE TITLE
reCAPTCHA badge with several language is not shown fully 

### ISSUE THREAD

**Issue by VasylShvorak** [magento/securify#203]
### Preconditions (*)

1. Magento with security-package 1.0-develop
2. Simple product is created

### Steps to reproduce (*)

1. Configure reCAPTCHA v2 Invisible with Language Code=de
2. Set Enable for Product Review=reCAPTCHA v2 Invisible
3. Go to product detail page
4. Open Review tab

### Expected result (*)

1. Recaptcha badge is shown fully without any cuts

### Actual result (*)

1. 
![RegressionDeLanguage](https://user-images.githubusercontent.com/26908019/79110976-454c3a00-7d84-11ea-8a9b-e38ff9dd221a.png)

Should be fixed and tested for all places where reCAPCHA is shown.

**UPD. Examples** 
## Also affected PayPal PayflowPro payment form
![image](https://user-images.githubusercontent.com/26908019/79113328-56e41080-7d89-11ea-8607-58e2ae5c7bb4.png)

##  login during Checkout
![recapha3_241-alpha2](https://user-images.githubusercontent.com/3409584/90660703-e0aa5b80-e20b-11ea-9ac0-3394f5afba67.png)

**Comment by engcom-Kilo** [comment]
@magento give me test instance

**Comment by engcom-Kilo** [comment]
@magento-engcom-team give me test instance

**Comment by nathanjosiah** [comment]
Hello @VasylShvorak  and thank your for your contribution! We are closing this issue as part of our backlog triaging process because we have decided not to work on this issue internally. You are still welcome to contribute to this if you wish and we can reopen if you want to work on it.

**Comment by nathanjosiah** [comment]
@VasylShvorak Please reopen your PR against the `develop` branch
