### ISSUE TITLE
Contact page. "Uncaught (in promise) null" error and stuck page if try to Submit form with reCAPTCHA incorrect API keys

### ISSUE THREAD

**Issue by engcom-Kilo** [magento/securify#217]
### Preconditions (*)

1. Enable "reCAPTCHA v2 Invisible" for Contact Page
2. Settings for "reCAPTCHA v2 Invisible" API keys - test/test (**incorrect API keys**)

### Steps to reproduce (*)

1. Go to Contact page
2. Fill form
3. Try to send

### Expected result (*)

1. Page is reloaded
2. The error message is shown
3. No errors in the console

### Actual result (*)

1. Page does not response
2. Errors in the browser console
![Contact_Us](https://user-images.githubusercontent.com/60192090/79971682-55a79780-849d-11ea-8d81-ba12241d9799.jpg)

**Comment by nathanjosiah** [comment]
Hello @engcom-Kilo  and thank your for your contribution! We are closing this issue as part of our backlog triaging process because we have decided not to work on this issue internally. You are still welcome to contribute to this if you wish and we can reopen if you want to work on it.
