### ISSUE TITLE
JS Error - TypeError: this.settings is undefined in FF && Uncaught TypeError: Cannot read property 'lang' of undefined in Chrome

### ISSUE THREAD

**Issue by xeontcs** [magento/securify#22]
When not configured/enabled.
JS Error - TypeError: this.settings is undefined in FF && Uncaught TypeError: Cannot read property 'lang' of undefined in Chrome in every product page.
### Preconditions

1. Magento 2.3.2

### Steps to reproduce

1. Any Product Page

### Expected result

1.  No JS errors

### Actual result

1. FireFox
TypeError: this.settings is undefined

2. Chrome
VM2267:72 Uncaught TypeError: Cannot read property 'lang' of undefined

**Comment by sdzhepa** [comment]
Due to significant refactoring and UI changes in Admin Panel for reCAPCTHA module in the scope of security-package for 2.4.x release, this bug is not actual anymore.
