### ISSUE TITLE
This site key is not enabled for the invisible captcha error

### ISSUE THREAD

**Issue by alaa-almaliki** [magento/securify#25]
The use of recaptcha as a reCaptcha Type results in an error **This site key is not enabled for the invisible captcha.** if **Yes** is selected to use recaptcha for the newsletter. This is because the newsletter use the invisible by default in https://github.com/magento/magespecialist_ReCaptcha/blob/2.3-develop/view/frontend/layout/default.xml#L60. It is not documented in the admin panel that by using the recaptcha for the newsletter, the invisible type should be selected.

### Preconditions

1.  Magento 2.3.2

### Steps to reproduce

1.  Select recaptcha for the reCaptcha Type
2. Select Yes to use recaptcha for newsletter as default

### Expected result

1. Should work as normal as earlier version without errors

### Actual result

1.  An error message appears on the frontend **This site key is not enabled for the invisible captcha.**

**Comment by sdzhepa** [comment]
Due to significant refactoring and UI changes in Admin Panel for reCAPCTHA module in the scope of security-package for 2.4.x release, this bug is not actual anymore.
