### ISSUE TITLE
Introduce events for reCaptcha rendering.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/securify#252]
### Summary (*)

We should not use timeouts and rely on html/css attributes in reCaptcha rendering process. (see code [here](https://github.com/magento/security-package/blob/1.0-develop/ReCaptchaFrontendUi/view/frontend/web/js/nonInlineReCaptchaRenderer.js)). Introduce events for making forms and modal windows visible/invisible.

**Comment by nathanjosiah** [comment]
Hello @engcom-Foxtrot  and thank your for your contribution! We are closing this issue as part of our backlog triaging process because we have decided not to work on this issue internally. You are still welcome to contribute to this if you wish and we can reopen if you want to work on it.
