### ISSUE TITLE
msp/twofactorauth/enabled config option doesn't work

### ISSUE THREAD

**Issue by MichaelThessel** [magento/securify#264]
### Preconditions (*)

1. 2.4

### Steps to reproduce (*)

1. Install 2.4
2. Follow instructions from `vendor/magento/module-two-factor-auth/README.md` and update `core_config_data` `msp/twofactorauth/enabled = 0`
3. Flush cache

```
mysql> select * from core_config_data where path = 'msp/twofactorauth/enabled';
+-----------+---------+----------+---------------------------+-------+---------------------+
| config_id | scope   | scope_id | path                      | value | updated_at          |
+-----------+---------+----------+---------------------------+-------+---------------------+
|      6278 | default |        0 | msp/twofactorauth/enabled | 0     | 2020-08-06 11:50:32 |
+-----------+---------+----------+---------------------------+-------+---------------------+
```

Followed instructions from `vendor/magento/module-two-factor-auth/README.md`:

```                                                                                 
Table `core_config_data`:                                                            
* `msp/twofactorauth/enabled`: Set to zero to disable 2fa globally  
```

Additionally the command line command referenced in the readme also doesn't exist:

```
If you messed up with two factor authentication you can disable it from command-line:    
                                                                                     
`php bin/magento msp:security:tfa:disable`    
```

```
  # bin/magento | grep tfa                                                                                                  
  security:tfa:google:set-secret                       Set the secret used for Google OTP generation.
  security:tfa:providers                               List all available providers
  security:tfa:reset                                   Reset configuration for one user
```

### Expected result (*)

1. When trying to log into admin 2fa is disabled

### Actual result (*)

1. 2fa is not disabled

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
fyi: @nathanjosiah @smiverma

**Comment by nathanjosiah** [comment]
Hey @MichaelThessel! Sorry for the confusion. That readme is outdated and will be updated soon. Please refer to https://devdocs.magento.com/guides/v2.4/security/two-factor-authentication.html for official documentation.

You cannot disable 2fa via configuration anymore. You can disable the entire module if you wish but be aware that just as with other security features, this will have implications for cloud customers and will soon constitute a violation of the terms of service in some cases.

**Comment by lagunacellar** [comment]
How does one go about logging into Admin backend after installing Magento 2.4.0 or 2.4.1 for the first time?  There is no built-in default SMTP settings.  2FA initiation email is not received, thus cannot be configured.  Disabling 2FA first -> configure SMTP -> enable 2FA -> activate authenticator after receiving email, seems to be the only way around this.  Does anyone know a better approach?

**Comment by nathanjosiah** [comment]
Hello @lagunacellar as I stated above we don't recommend disabling 2fa in production environments. Since we require at least two factors of authentication to login, email is the only available option without enabling additional providers which is the default state of a fresh 2.4.0+ installation. Email is a system requirement for Magento and is critical for many components such as receipts, reset password, 2fa, and more. For development environments there are many easy options for setting up fake email systems or you can simply disable 2fa. For production, email is required for proper behavior of Magento.

**Comment by lagunacellar** [comment]
We want 2FA in production environment. Disabling it temporarily to set up SMTP and 2FA is strictly used in development environment only, it seems to be the easy way to work around the limitations.
