### ISSUE TITLE
2FA - Admins with custom resource access can't setup 2FA or login

### ISSUE THREAD

**Issue by jaxtheking** [magento/securify#266]
On my site, I have created a custom user role for shop admins. They have access to pretty much all of the content and tools (Dashboard, Sales, Catalog, Carts, Customer, Marketing, Content, Reports) but none of the settings (Stores or Systems).

After upgrading to Magento 2.4.0 and enabling Two-Factor Authentication, I had no problem with my admin user (with unlimited resource access) to setup 2FA and log into the BO.
However the shop admins, after entering their login credentials, are not able to setup 2FA as an email is not sent to them and they receive an error stating they do not have permissions to see the content - find full details below.

I have discovered that if I give their user role access to `Stores > Settings > Configuration > Two Factor Auth` and `System > Permissions > Two Factor Auth`, then they can proceed with the setup process and eventually login.
If you only grant the first permission, the page goes into a loop (too many redirects due to: Invalid security or form key. Please refresh the page.). Granting only the second permission, does nothing. Grant both, and it works.

As a consequence, now shop admins have access to the 2FA configuration and could - potentially - tweak it or disable it altogether.
Is this really how it's supposed to work? I did not find any reference to this on the Magento guide to 2FA.
Please advice.

### Preconditions (*)

1. Magento 2.4.0
2. CentOS 6, Apache 2.4, MySQL 5.7, PHP 7.3 FPM

### Steps to reproduce (*)

1. Make sure 2FA is setup in Magento - I only have enabled Google Authenticator
2. Create a User Role with the typical permissions for a shop admin: Dashboard, Sales, Catalog, Carts, Customer, Marketing, Content, Reports. Do not give access to Stores or Systems
3. Add a new user with the user role created above
4. Now try logging in with the new user's credentials
5. At this point you should be prompted that you do not have permissions to see this content - the user is stuck, unable to setup 2FA as an email is never sent

### Expected result (*)

1. An email with a link to setup 2FA should be sent
2. The user should see the following message:
`You need to configure Two-Factor Authorization in order to proceed to your store's admin area. An E-mail was sent to you with further instructions`

### Actual result (*)

1. An email is never sent
2. The user cannot proceed and sees the following message:
`Sorry, you need permissions to view this content.`
3. The 'Return to previous page' link does nothing

![error](https://user-images.githubusercontent.com/3924723/90139918-e833b580-dd70-11ea-83a0-091133c870ba.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
@nathanjosiah @smiverma 

Could you please have a look?

**Comment by nathanjosiah** [comment]
Hey @jaxtheking! There has been some confusion about the 2fa permissions and we do plan to update the labels on the ACL resources to make it more clear. There are two resources on the role configuration page. The first one allows the user to configure the global 2fa settings like which providers are available. This would only be for main admins with higher permissions. The second one allows users to simply use 2fa at all. For a normal user, only the second permission is needed and without this they will see the permissions error you show above.

**Comment by jaxtheking** [comment]
Hi @nathanjosiah, thanks for getting back to me.
I agree that the label (or the positioning perhaps as it seems to grant access to a menu item, like the rest of the permissions in the same group) of the second permission (System > Permissions > Two Factor Auth) led to confusion.

I would consider critical adding a paragraph about this in the 2FA setup guide page.
However, I can't help thinking: if 2FA is enabled globally, do we also need a per-role permission? If we do, maybe it should be set automatically for all roles upon enabling the module.
Alternatively, it all could be left as is and per-role permissions could be added in a tab directly to the 2FA configuration page.
Just my 2¢...

Anyway, I insist there is a bug with this - at least on my site. When I enable only the second permission (without the first), the page goes in a redirection loop. Please see the image below:

![error2](https://user-images.githubusercontent.com/3924723/90262829-b9880e80-de46-11ea-8d54-f8343103e5fb.png)

Can you reproduce it yourself?

**Comment by jaxtheking** [comment]
Hi @nathanjosiah, thanks for getting back to me.
I agree that the label (or the positioning perhaps as it seems to grant access to a menu item, like the rest of the permissions in the same group) of the second permission (System > Permissions > Two Factor Auth) led to confusion.

I would consider critical adding a paragraph about this in the 2FA setup guide page.
However, I can't help thinking: if 2FA is enabled globally, do we also need a per-role permission? If we do, maybe it should be set automatically for all roles upon enabling the module.
Alternatively, it all could be left as is and per-role permissions could be added in a tab directly to the 2FA configuration page.
Just my 2¢...

Anyway, I insist there are bugs with this - at least on my site:
1. When I enable only the second permission (without the first), it still showing me the permission error I originally posted
1. When I enable only the first permission (without the second), the page goes in a redirection loop. I am aware this may not make a lot of sense to do, but surely this case should be handled more gracefully?
Please see the image below:

![error2](https://user-images.githubusercontent.com/3924723/90263951-467f9780-de48-11ea-88f2-755b24b8aad9.png)

Are you able to reproduce these errors yourself?

**Comment by nathanjosiah** [comment]
> if 2FA is enabled globally, do we also need a per-role permission?
It's a good question. Right now our view is yes. Merchants may want some users to use a separate authentication mechanism. There is also the ability to browse magento pages with only one factor that some merchants could customize to work for them.

As for the bugs, I am unable to reproduce this behavior. I'm not sure if the automated magento instances have been upgraded to use 2fa yet. Let's see.

**Comment by nathanjosiah** [comment]
@magento give me a magento 2.4 instance

**Comment by nathanjosiah** [comment]
@magento give me 2.4-develop instance

**Comment by nathanjosiah** [comment]
Looks like it's not. I created an instance over on https://github.com/magento/magento2/issues/29556 but it looks like it's just magento core and not 2fa. I would see if you can investigate what's going on with your instance.

**Comment by nathanjosiah** [comment]
@jaxtheking Were you able to figure out what's going on here?

**Comment by jaxtheking** [comment]
Hi @nathanjosiah,
I meant to give it a try but in all honesty all of my time is currently taken away by other two projects.
I'm not a Magento/backend developer so I'm not sure my attempt would have come up to anything.
It's definitely still happening on our site though.

**Comment by nathanjosiah** [comment]
Not sure how I misread this issue the last time I looked but this is actually a known issue and was already fixed and will ship with the 2.4.2 release or you can manually install the latest 1.0-develop branch of the security package (or just the code from 2fa). Here is the git patch for this issue if it would be helpful https://github.com/magento/security-package/commit/f46251ef0eaf6c9ca282f2644e1245a3b0bf7028.patch

(this is actually the second "Known Issue" on the 2.4.1 release notes https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-1.html#known-issues)

**Comment by jaxtheking** [comment]
Great news then, thanks for confirming. I'll try out the patch.

**Comment by nathanjosiah** [comment]
Forgot to mention this was fixed in #276
