### ISSUE TITLE
[EE and B2B]Recaptcha badge is not shown on customer account edit page

### ISSUE THREAD

**Issue by engcom-Delta** [magento/securify#268]
### Preconditions (*)

1. Magento 2.4.1 EE and B2b ; Issue is not repo on CE 2.4.1
2. reCAPTCHA v2 ("I am not a robot") is configured 
:warning: **Note:** Also reproducible with reCAPTCHA v2-v3 Invisible
:warning: **Note:** Issue is not reproducible on [magento CE 2.4.1](https://github.com/magento/magento2ce/tree/2.4.1-develop) + [security-package 1.0-develop](https://github.com/magento/security-package)
![image](https://user-images.githubusercontent.com/51681379/91463238-d0d9e980-e893-11ea-80d0-8953f81910b2.png)

### Steps to reproduce (*)

1. Set Enable for Edit Customer Account=reCAPTCHA v2 ("I am not a robot")
2. Created customer
3. Log in as created customer
4. Go to My Account->Account Information 

### Expected result (*)

1. reCAPTCHA v2 ("I am not a robot") is displayed

### Actual result (*)

1. reCAPTCHA v2 ("I am not a robot") is not shown
2. Customer is not able to edit `First Name` and `Last Name` fileds
![Peek 2020-08-27 17-57](https://user-images.githubusercontent.com/51681379/91459391-47c0b380-e88f-11ea-82f4-ed5f9109c079.gif)

### Additional Information
- https://github.com/magento/security-package/issues/268#issuecomment-682015152

> Possibly caused by #155
> 
> It seems templates for My Account on Storefront are different for each edition.
> And recapcha was added to CE but not into EE and B2B templates.
> 
> As a result, ReCaptcha is existed but not shown so Customer is not able to pass it.

**Comment by sdzhepa** [comment]
Possibly caused by https://github.com/magento/security-package/pull/155

It seems templates for My Account on Storefront are different for each edition. 
And recapcha was added to CE but not into EE and B2B templates.

As a result, ReCaptcha is existed but not shown so Customer is not able to pass it.

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug
