### ISSUE TITLE
2FA - Allow Enable/Disable option for Dev Environment

### ISSUE THREAD

**Issue by vkranjith** [magento/securify#271]
### Description (*)
The module MSP_TwoFactorAuth used to provide a simple enable/disable feature in the admin panel, which was quite convenient when it comes to developers in the local dev environment. When this module was taken up by Magento in 2.4.0, the module lost this convenient feature. Now, because of this, a developer is not able to get the 2FA email from his/her dev machine, where normally they won't have the email server enabled due to various reasons, and stopping the developer from logging into Magento's admin panel. One work around suggested by many people is to disable the module. But this could be hectic when the developer need to enable and disable the module based on if they need to commit or take a pull of the `app/etc/config.php` file.

### Expected behavior (*)
The developer is able to easily disable the 2FA in his dev environment and doesn't have to worry about that setting when he pulls/pushes any code change.

### Benefits
The feature to enable/disable the 2FA could be hidden from normal Admin user but still made available to developers. This way we need not worry about an Admin user accidentally disabling the feature as only a developer will be able to disable it through `app/etc/env.php` configuration.

### Additional information
The configuration setting can be provided inside the module's `etc/config.xml` file and this configuration can be controlled using an entry in the `app/etc/env.php` file. As the env.php file is environment specific and will never be committed, there won't be any chance for accidentally pushing this file to higher environment and disabling this security feature. Also, because this is a file level configuration, an Admin user can never accidentally turn it off.

**Comment by vkranjith** [comment]
@magento I am working on this

**Comment by nathanjosiah** [comment]
Hey @vkranjith thanks for the submission! I can run this by the business decision makers on this but the stance has been a hard no on creating an official disabling option of any kind. You can always turn off the whole module on your dev environment which would do the same thing. Not being able to access email hasn't been a good reason for decision making with features historically because it's a system requirement that many features of Magento expect to be available.

**Comment by vkranjith** [comment]
Hi @nathanjosiah ,

Thanks for considering this. But I really feel that this is needed for a developer at least. And I have seen a lots of discussions around this in GitHub and other places where developers are looking for this as disabling and re-enabling the module every time, in my opinion, is the worst developer experience. I started seeing this issue in our Magento Cloud instance where we don't get any sort of email service on the Integration environments to setup the 2FA, which is annoying when compared to the features available in 2.3.x.

**Comment by nathanjosiah** [comment]
I understand the concern. As I mentioned it's been a product and security decision that outweighed the developer experience. As I mentioned I will see if we can reevaluate this and get it approved.

**Comment by nathanjosiah** [comment]
After some delays and discussions we have decided to not make this change. There are many options for developers to turn this off for local development that don't involve an official toggle and for that reason as well as the policy-based reason I provided above, we are going to close this ticket. Thank you!
