### ISSUE TITLE
[B2B only] Save button is not displayed on Edit Account Information page

### ISSUE THREAD

**Issue by engcom-Delta** [magento/securify#274]
### Preconditions (*)

1. Magento 2.4.1 B2B ; Issue is not reproducible on EE 2.4.1, CE 2.4.1
2. reCAPTCHA v2 ("I am not a robot") is configured 
:warning: **Note:** Also reproducible with reCAPTCHA v2-v3 Invisible

### Steps to reproduce (*)

1. Go to Stores->General->B2B Features
2. Set Enable Company=Yes
3. Set Enable for Edit Customer Account=reCAPTCHA v2 ("I am not a robot")
4. Created customer
5. Log in as created customer
6. Go to My Account->Account Information 

### Expected result (*)

1. Save button is displayed, customer is able to save new data into  Account Information
![image](https://user-images.githubusercontent.com/51681379/93098631-c1d6a200-f6af-11ea-9092-a0f543fd0ce6.png)

### Actual result (*)

1. Save button is overlapped by recaptcha badge
2. Customer is not able to save new data into  Account Information
![image](https://user-images.githubusercontent.com/51681379/93057693-0134cc80-f677-11ea-8117-516f383ae010.png)

![Peek 2020-09-14 17-35](https://user-images.githubusercontent.com/51681379/93099451-b0da6080-f6b0-11ea-8e55-36c7d1f4a9d1.gif)

**Comment by sdzhepa** [comment]
The issue will be fixed and delivered in the scope of internal Jira ticket `MC-37638`
