### ISSUE TITLE
Magento 2.4.0 - Magento_ReCaptchaFrontendUi loads assets on every page

### ISSUE THREAD

**Issue by gondas33** [magento/securify#275]
:i: Please investigate how much work this would be to fix and how much of a problem this actually is. ~~--~~ 
1. Magento_ReCaptchaFrontendUi/js/registry.min.js loads
1. Magento_ReCaptchaFrontendUi/js/ui-messages-mixin.min.js loads

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Spike

**Comment by timpea** [comment]
Is there a related commit that fixes this?

**Comment by ihor-sviziev** [comment]
@sidolov could you please give us more details, was the issue fixed?
