### ISSUE TITLE
Security.txt->General setting has the extra line at the bottom

### ISSUE THREAD

**Issue by engcom-Delta** [magento/securify#279]
### Preconditions (*)

1. Magento 2.4-develop + Security Package 1.0-develop

### Steps to reproduce (*)

1. Go to the Backend
2. Go Configuration->Security->Security.txt
3. Check the display of General section

### Expected result (*)

1. It has no extra line at the bottom (the normal style)

### Actual result (*)

1. It has the extra line at the bottom
![image](https://user-images.githubusercontent.com/51681379/96092951-329df380-0ed4-11eb-86fe-e7ccc1bc4bae.png)

**Additional information**:
Possible reason https://github.com/magento/magento2/issues/23676#issuecomment-528064368

**Comment by chiranjeevi-cj** [comment]
@magento I am Working on this

**Comment by chiranjeevi-cj** [comment]
@engcom-Delta This issue is in the wrong repo I think. can you please verify that?

**Comment by chiranjeevi-cj** [comment]
@engcom-Delta What should I do now?

**Comment by nathanjosiah** [comment]
Hello @chiranjeevi-cj  and thank your for your contribution! We are closing this issue as part of our backlog triaging process because we have decided not to work on this issue internally. You are still welcome to contribute to this if you wish and we can reopen if you want to work on it.
