### ISSUE TITLE
Captcha Modules do not contain CSP Whitelist for google

### ISSUE THREAD

**Issue by gwharton** [magento/securify#281]
### Preconditions (*)

1. 2.4.1 via composer

### Steps to reproduce (*)

1. Deploy 2.4.1 from composer

```
Store -> Configuration -> Security -> Google ReCaptcha Storefront
  ReCaptcha v3 Invisible -> Google Api Website Key = test (Doesnt need to be valid)
  ReCaptcha v3 Invisible -> Google Api Website Secret = test (Doesnt need to be valid)
  Storefront -> Enable for Newsletter Subscription = ReCaptcha v3 Invisible
  Save Config
Open developer tools console
Go to Frontend
```

### Expected result (*)

1. There should be no CSP warnings under normal operation

### Actual result (*)

1. Alas, there are some

![image](https://user-images.githubusercontent.com/30697781/97557025-220c7380-19d2-11eb-9dd0-0bd4199cc865.png)

**Comment by AlexMaxHorkun** [comment]
Thanks for bringing this up! We already have a story to address this issue in the next patch release

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MC-38797) is successfully created for this issue.

**Comment by JeffersonTeixeira** [comment]
The issue still present in Magento 2.4.2
