### ISSUE TITLE
Paypal Recaptcha Disappear In Checkout

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/securify#282]
### Preconditions (*)

1.  Install Magento and configure reCaptcha
2. Enable reCaptcha in checkout

### Steps to reproduce (*)

1. Add product to cart
2. Go to Checkout
3. Save the shipping address
4. Edit the billing address
5. click update button to update the address.
6. captcha is disappear in checkout.

### Expected result (*)

1. Order need to be placed

### Actual result (*)

1. It throw Invalid recaptcha.

**Comment by nathanjosiah** [comment]
@magento export issue to Jira MC project as Bug

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MC-39278) is successfully created for this issue.

**Comment by svitja** [comment]
@vijay-prevaj Hi, I can't reproduce it. Can you provide more details, save video?
