### ISSUE TITLE
Allow use reCAPTCHA globally

### ISSUE THREAD

**Issue by thomas-kl1** [magento/securify#288]
### Description (*)

As a merchant I want to select the captcha domain:

- https://www.google.com/recaptcha/api.js
- https://www.recaptcha.net/recaptcha/api.js

See Google Documentation: https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

### Expected behavior (*)
Allow to use reCaptcha even in countries were google is known to be limited.

### Benefits
Could be used by any merchant worldwide.

### Additional information
I would like to work on this, please point me to the correct direction to:

- Add the settings (adminhtml ui right?)
- Add the setting to api (what package)?
- Update the following files to use the alternative domain:
  - Magento/ReCaptchaFrontendUi/view/web/js/reCaptchaScriptLoader.js
  - Magento/ReCaptchaUser/view/adminhtml/templates/recaptcha.phtml

https://github.com/magento/security-package/pull/289

**Comment by thomas-kl1** [comment]
@magento I am working on this

**Comment by thomas-kl1** [comment]
@nathanjosiah do not mark this issue as "Progress: done" as the feature as not been implemented. Please re-open it

**Comment by nathanjosiah** [comment]
@thomas-kl1 The labels are changed from our automation. I don't have fine control over them. I will re-open

**Comment by nathanjosiah** [comment]
Closing all non-active issues. This has been open and not really worked on for 213 days. We are not going to work on this internally but if you want to commit to working on it and stabilizing your PR I will reopen.

**Comment by thomas-kl1** [comment]
@nathanjosiah maybe you could change the label, it's confusing
