### ISSUE TITLE
Mark interfaces and blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/securify#290]
The following interfaces and blocks should be marked as API in future-develop branch

1. security-package/TwoFactorAuth/Api/AdminTokenServiceInterface.php
1. security-package/TwoFactorAuth/Api/AuthyAuthenticateInterface.php
1. security-package/TwoFactorAuth/Api/AuthyConfigureInterface.php
1. security-package/TwoFactorAuth/Api/CountryRepositoryInterface.php
1. security-package/TwoFactorAuth/Api/Data/AdminTokenResponseInterface.php
1. security-package/TwoFactorAuth/Api/Data/AuthyDeviceInterface.php
1. security-package/TwoFactorAuth/Api/Data/AuthyRegistrationPromptResponseInterface.php
1. security-package/TwoFactorAuth/Api/Data/CountryInterface.php
1. security-package/TwoFactorAuth/Api/Data/CountrySearchResultsInterface.php
1. security-package/TwoFactorAuth/Api/Data/DuoDataInterface.php
1. security-package/TwoFactorAuth/Api/Data/GoogleAuthenticateInterface.php
1. security-package/TwoFactorAuth/Api/Data/GoogleConfigureInterface.php
1. security-package/TwoFactorAuth/Api/Data/U2fWebAuthnRequestInterface.php
1. security-package/TwoFactorAuth/Api/Data/UserConfigInterface.php
1. security-package/TwoFactorAuth/Api/Data/UserConfigSearchResultsInterface.php
1. security-package/TwoFactorAuth/Api/DuoAuthenticateInterface.php
1. security-package/TwoFactorAuth/Api/DuoConfigureInterface.php
1. security-package/TwoFactorAuth/Api/EngineInterface.php
1. security-package/TwoFactorAuth/Api/Exception/NotificationExceptionInterface.php
1. security-package/TwoFactorAuth/Api/GoogleAuthenticateInterface.php
1. security-package/TwoFactorAuth/Api/GoogleConfigureInterface.php
1. security-package/TwoFactorAuth/Api/ProviderInterface.php
1. security-package/TwoFactorAuth/Api/ProviderPoolInterface.php
1. security-package/TwoFactorAuth/Api/TfaInterface.php
1. security-package/TwoFactorAuth/Api/TfaSessionInterface.php
1. security-package/TwoFactorAuth/Api/TfatActionsInterface.php
1. security-package/TwoFactorAuth/Api/U2fKeyAuthenticateInterface.php
1. security-package/TwoFactorAuth/Api/U2fKeyConfigReaderInterface.php
1. security-package/TwoFactorAuth/Api/U2fKeyConfigureInterface.php
1. security-package/TwoFactorAuth/Api/UserConfigManagerInterface.php
1. security-package/TwoFactorAuth/Api/UserConfigRepositoryInterface.php
1. security-package/TwoFactorAuth/Api/UserConfigRequestManagerInterface.php
1. security-package/TwoFactorAuth/Api/UserConfigTokenManagerInterface.php
1. security-package/TwoFactorAuth/Api/UserNotifierInterface.php
1. security-package/TwoFactorAuth/Model/AlertInterface.php
1. Magento\TwoFactorAuth\Block\ConfigureLater
1. Magento\TwoFactorAuth\Block\Configure
1. Magento\TwoFactorAuth\Block\Provider\U2fKey\Configure
1. Magento\TwoFactorAuth\Block\Provider\U2fKey\Auth

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Story

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by nathanjosiah** [comment]
fixed in https://github.com/magento-commerce/security-package/pull/38

**Comment by fredden** [comment]
> fixed in https://github.com/magento-commerce/security-package/pull/38

https://github.com/magento/security-package/commit/8d5c176194b535f379d985d130d6999edb08e00d
