### ISSUE TITLE
Not able to use captcha multiple times in same page

### ISSUE THREAD

**Issue by JeffersonTeixeira** [magento/securify#293]
### Summary (*)
I'm developing a module to allow customer Login/reset password from a popup (modal). The module is available in all pages. I'm able to render the recaptcha normally, but if I'm in a page that already has the recaptcha rendered, it can't have it rendered in modal. The popup content for reset password is loaded by ajax, then I call .applyBindings() (knockoutJs) and $('popup').trigger('contentUpdated') after it is attached in html, and not even this way it shows up. Is there a way to have it working?

### Examples (*)
If I'm in create account page (with recaptcha rendered) then I open my modal with another form which requires recaptcha, it isn't rendered in modal.

### Proposed solution
Allow using multiple recaptcha in same page

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Story

**Comment by nathanjosiah** [comment]
@JeffersonTeixeira Can you please provide a concrete example of code in a gist or something where we could easily reproduce this?

**Comment by nathanjosiah** [comment]
@JeffersonTeixeira If you can provide an example for us to work with I can probably reopen but for now I'm going to close this.
