### ISSUE TITLE
Unable to Plugin to \Magento\TwoFactorAuth\Observer\ControllerActionPredispatch

### ISSUE THREAD

**Issue by NathanDayFE** [magento/securify#296]
### Preconditions (*)
1. Magento 2.4 

### Steps to reproduce (*)
1. Attempt to plugin to `\Magento\TwoFactorAuth\Observer\ControllerActionPredispatch::execute` will not work due to \Magento\TwoFactorAuth\TestFramework\ControllerActionPredispatch being a preference of it
2. Attempt to plugin to \Magento\TwoFactorAuth\TestFramework\ControllerActionPredispatch will work in dev mode as interceptors are generated on the fly
3. Switch to production mode and run `setup:di:compile`
4. No interceptor is generated for `\Magento\TwoFactorAuth\TestFramework\ControllerActionPredispatch` becuase it has `<VENDOR_MODULE>/Test` in its filepath (excluded in `\Magento\Setup\Module\Di\Code\Reader\ClassesScanner::extract`)

### Expected result (*)
1. should be able to plugin to `\Magento\TwoFactorAuth\Observer\ControllerActionPredispatch::execute`

### Actual result (*)
1. Unable to plugin to method due to preference

### Suggested solution
- Migrate the `\Magento\TwoFactorAuth\TestFramework\ControllerActionPredispatch` preference to be a plugin keeping the `\Magento\TwoFactorAuth\Observer\ControllerActionPredispatch` interceptor in play

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project MC as Bug

**Comment by fredden** [comment]
This has been fixed in https://github.com/magento/security-package/pull/297
