### ISSUE TITLE
Outdated endroid/qr-code dependecy

### ISSUE THREAD

**Issue by tmotyl** [magento/securify#30]
This package requires very old and outdated version of endroid/qr-code v2.5(from 2017)
The endroid/qr-code v2.5 depends on some old symfony modules (like symfony/options-resolver). 
This prevents from using other packages wich also requires symfony components but with higher versions in Magento2 projects.

For example requiring phpro/grumphp will fail on a fresh magento 2 project.
`composer require --dev phpro/grumphp`
Because of the conflicting symfony bundles version.

**Comment by nathanjosiah** [comment]
@tmotyl Did you look at the dependency tree and determine if there is a version that we could safely switch to without affecting anything else?

**Comment by tmotyl** [comment]
I did, but it was so long ago, I don't have the notes any more.

**Comment by nathanjosiah** [comment]
Actually this will be fixed in https://github.com/magento/security-package/pull/151/files#diff-917d344616cb180e8879bdc028fcd50e
