### ISSUE TITLE
Publish a new release of TwoFactorAuth extension

### ISSUE THREAD

**Issue by pitbulk** [magento/securify#318]
### Summary
The latest release of TwoFactorAuth is the 1.1.2 dated on 13 Jul 2021

Such release includes the requirement of the unecesary package phpseclib/phpseclib that is creating installation issues when I'm trying to install it.

### Proposed solution
Make a new release with the code available on develop branch.

**Comment by nathanjosiah** [comment]
Latest tag available is 1.1.4. Closing this issue
