### ISSUE TITLE
Wrong version in 1.1.3-p1 metapackage composer.json

### ISSUE THREAD

**Issue by Vinai** [magento/securify#321]
### Preconditions (*)
The version in the compser.json of the 1.1.3-p1 tag release metapackage wasn't updated.

Expected version: 1.1.3-p1
Actual version: 1.1.3

Reference https://github.com/magento/security-package/blob/1.1.3-p1/_metapackage/composer.json#L5

This causes issues with tooling expecting the version in the composer.json file to match the composer package.

**Comment by damienwebdev** [comment]
This winds up with:

```bash
  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.4-p1 -> satisfiable by magento/product-community-edition[2.4.4-p1].
    - magento/product-community-edition 2.4.4-p1 requires magento/security-package 1.1.3-p1 -> found magento/security-package[1.0.0, ..., 1.1.4] but it does not match the constraint.
```

**Comment by nathanjosiah** [comment]
The versions have been fixed and resynced

**Comment by damienwebdev** [comment]
Thank you @nathanjosiah !
