### ISSUE TITLE
Remove trust this device option from login page when it is disabled

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/securify#33]
### Preconditions

1. Google Authenticator, Authy and U2F Devices are enabled as 2FA methods
2. 2FA is globally enabled
3. No methods are forced

### Steps to reproduce

1. Switch **Enable "trust this device" option** to **No**
2. Save configuration
3. Perform setup
4. Try to log in with "trust this device" checked using Google Authenticator

### Expected result

1. People are not confused that the device will be saved

### Actual result

1. The device is not saved as expected for Merchant who performed setup but is not expected for other Merchants

**Comment by nathanjosiah** [comment]
Thank you for opening this issue! I am closing this along with others due to 2fa currently undergoing a very large internal rewrite/refactor this change will not be needed in the new version.
