### ISSUE TITLE
Fix alignment for 2FA in User selection tab

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/securify#34]
### Preconditions

1. 1 or more 2FA methods enabled
2. 2FA is globally enabled
3. No methods that are forced

### Steps to reproduce

1. Navigate to 2FA tab of some User in Stores->Settings->All Users

### Expected result

1. Checkboxes and labels are properly aligned

### Actual result

1. Checkboxes and labels aren't properly aligned
![image](https://user-images.githubusercontent.com/11827230/63592505-67f1ce80-c5ba-11e9-92a1-9e741f39afe9.png)

**Comment by mohanelamurugan** [comment]
@okorshenko @sdzhepa  
Can you please assign this to me. I would like to work on this

**Comment by nathanjosiah** [comment]
@mohanelamurugan Thank you for your interest in this! 2fa is currently undergoing a massive internal rewrite/refactor and we can't accept contributions at this time. This change in particular will not be an issue in the new version as this portion of the feature has been removed.
