### ISSUE TITLE
Update db_schema_whitelist.json

### ISSUE THREAD

**Issue by naydav** [magento/securify#43]
Update db_schema_whitelist.json for ALL of the modules according to
```
When creating a new table, remember to generate the db_schema_whitelist.json file.
```

Details: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html#create-a-table

> When creating a new table, remember to generate the db_schema_whitelist.json file.

**Comment by michaelyu0123** [comment]
No longer applicable.
